### ISSUE TITLE
inconsistent scrollbar width

### ISSUE THREAD

**Issue by mihado** [satya164/Evolve#2]
hi there,
it seems like the width of the scroll bar varies between different websites in Firefox. I cannot seem to reproduce this behaviour in any other applications. (Please check the included screen-shot).

Do you have any idea what is/are causing this issue?

If I want to reduce the size of the scrollbar, which part of the css should I change? thanks

![workspace 1_003](https://f.cloud.github.com/assets/940981/441322/d1dfa1c4-b116-11e2-9a27-2beab5bb4cea.png)

**Comment by satya164** [comment]
In GTK2, gtkrc => GtkScrollbar::slider-width = 9
In GTK3, gtk-widgets.css => -GtkRange-slider-width: 13;

I'll try to fix the issue. Thanks.
