### ISSUE TITLE
Close button in window title black color

### ISSUE THREAD

**Issue by csoriano1618** [satya164/Evolve#3]
(Using gnome 3.10 in fedora 20.)
Hi, seems there's a problem with the window title close button color. 
![screenshot from 2013-11-25 15 26 08](https://f.cloud.github.com/assets/1755514/1613704/a919cb68-55dd-11e3-885d-2fcc83800bf3.png)

Also, aside gedit that I show in the next image, I can't see that close button border in other CSD windows like nautilus

I was expecting everywhere something like:
![screenshot from 2013-11-25 15 27 30](https://f.cloud.github.com/assets/1755514/1613710/c4015996-55dd-11e3-8907-fb96b99eda80.png)
Thanks for your work!

**Comment by satya164** [comment]
Hmm... That is epiphany, right? May be I'll need to add custom styles.

**Comment by csoriano1618** [comment]
That was firefox. But just noticed it is not an issue in arch, so I guess it was some gsetting issue I was having in fedora.

Aside that, as you can see in gedit (from git, branch redesign2) the close button have a border in hover state, which makes it visible which area is clickable and if are you inside that area (adwaita do the same) Not sure why but gedit from git is the only application that do that in evolve theme. I think it would be cool to have that in all window title close buttons.

Thanks!

**Comment by satya164** [comment]
Are you using the Evolve metacity theme?

**Comment by csoriano1618** [comment]
Not sure it is what you want to know, but I'm just using default gnome(so using mutter, not metacity) with default fedora 20. The same for arch (antergos).

And the theme is downloaded from here at github, so using I'm using master.
Is it what you want to know?

**Comment by satya164** [comment]
What is the output of `gsettings get org.gnome.desktop.wm.preferences theme`

Also, the theme should be installed in /usr/share/themes for the metacity/mutter theme to work. You can also install in ~/.local/share/themes, but GTK2 themes won't work this way.

**Comment by csoriano1618** [comment]
I had some issue with permissions in fedora with /usr/share/themes, so I already fixed the black close button issue solving the permissions issue. Just ignore that issue, and sorry for the noise.

But aside that, maybe it would be cool to have the close button border on hover as adwaita does to make visible which area is clickable and make you know if you are inside that area. what do you think? =)

Thanks!

**Comment by satya164** [comment]
Hmm... Adding a border will make the titlebar enormous. So not an option. Sorry :(

**Comment by csoriano1618** [comment]
oh, csd windows has a fixed size header bar. So I guess...if you add a border to the close button, it just will looks the same in non csd window and csd windows, not like now...no?
Of course whatever you want! And thanks for considering it =)

**Comment by satya164** [comment]
CSD has a fixed size. But I want to make the metacity and CSD close buttons look similar. So...
